apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: gpu
spec:
  rules:
    - name: "RTX 3090"
      labels:
        "node-role.kubernetes.io/gpu": "true"
        "nvidia.com/gpu": "rtx-3090"
      taints:
        - key: "nvidia.com/gpu"
          effect: "NoSchedule"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["10de"] }
            device: { op: In, value: ["2204"] }
        - feature: system.name
          matchExpressions:
            nodename: { op: InRegexp, value: ["^g"] }

    - name: "RTX 4090"
      labels:
        "node-role.kubernetes.io/gpu": "true"
        "nvidia.com/gpu": "rtx-4090"
      taints:
        - key: "nvidia.com/gpu"
          effect: "NoSchedule"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["10de"] }
            device: { op: In, value: ["2684"] }
        - feature: system.name
          matchExpressions:
            nodename: { op: InRegexp, value: ["^g"] }