apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: juicefs-dev
  metaurl: "redis://:<custom-password>@172.19.12.1:6379/1"
  configs: "{ceph-conf: /etc/ceph}"
  storage: ceph
  bucket: ceph://juicefs
  access-key: "ceph"
  secret-key: "client.juicefs"
  envs: "{TZ: Asia/Shanghai}"
  # format-options: trash-days=1,block-size=4096